### ISSUE TITLE
documents must be in pdf format

### ISSUE THREAD

**Issue by patinusb** [RobotML/RobotML-and-Portal#12]
It is mandatory to avoid editable format. Everything should be translated to pdf.

**Comment by nmorette** [comment]
In order to avoid editable format, presentations have been translated in the ppsx format (only readable). I don't have found a solution to keep videos in the pdf format, but if anyone know how to do that I will then change to pdf.

**Comment by patinusb** [comment]
Video is always a publishable format due to size. Thus there is no issue with that.
