### ISSUE TITLE
target for robotml documentation needed

### ISSUE THREAD

**Issue by patinusb** [RobotML/RobotML-and-Portal#36]
Nowadays we did not define how to proceed when publishing documentation. Here in this issue I am proposing something.

_github.com/RobotML/RobotML-documentation_ provides sphinx based repository. When considering an update, there is a website dedicated to verification of correctness of generated doc. It is robotml.github.io that is used for this process. Published documentation (when correctness has been verified) nevertheless should be located on the portal and thus there is the need of an uploading area dedicated to this part of the documentation. 

This issue is dedicated to the creation of this area and how to introduce this documentation correctly in the portal. This is one of the very important issue...

**Comment by patinusb** [comment]
A question remains on how to render this upload easy. In fact documentation is a set of files and folders in mixed format (html, pdf, png...). Using ftp could be very tidy... Is there an easy way to synchronise folders (through an rsync perhaps?).

**Comment by patinusb** [comment]
This is linked to issue #2

**Comment by nmorette** [comment]
A Rsync and a ftp protocol have been opened in order to update the documentation.
